### ISSUE TITLE
Callback doesn't accept parameters

### ISSUE THREAD

**Issue by slopesidecreative** [Nicolab/gulp-if-else#1]
It appears that the callback functions don't accept parameters. 

For example, this errors when calling replace() with params:

gulp.task('google-map', function(){
  var indexPath = path.join(config.paths.source, 'index.html');
  var isProd = process.env.NODE_ENV === 'prod';

  return gulp.src([indexPath])
  .pipe(ifElse(isProd,replace(config.paths.gMapDev, config.paths.gMapProd)))
  .pipe(gulp.dest(config.paths.build));

});

**Comment by Nicolab** [comment]
Hello,

It is because you do not pass a callback but the return of the `replace()` function (directly executed in your code).

You must pass a callback (which will be executed), like this: 

``` js
gulp.task('google-map', function(){
  var indexPath = path.join(config.paths.source, 'index.html');
  var isProd = process.env.NODE_ENV === 'prod';

  return gulp.src([indexPath])
    .pipe(ifElse(isProd, function() { 
      return replace(config.paths.gMapDev, config.paths.gMapProd);
    }))
    .pipe(gulp.dest(config.paths.build));
});
```

See [example](https://github.com/Nicolab/gulp-if-else#usage)
